# Generated by Django 3.2.5 on 2021-07-15 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='safebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialmanager.safebox')),
                ('payer', models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialmanager.safebox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
