# Generated by Django 3.2.5 on 2021-09-04 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='safebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('balance', models.BigIntegerField(default=0)),
                ('payment_gateway', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='safebox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialmanager.safebox')),
                ('payer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialmanager.safebox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('safebox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box', to='financialmanager.safebox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
