# Generated by Django 3.2.5 on 2021-07-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financialmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='payer',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to=settings.AUTH_USER_MODEL),
        ),
    ]
