# Generated by Django 3.2.5 on 2021-07-21 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financialmanager', '0002_alter_withdraw_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='safebox',
            name='payment_gateway',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='invite_id',
            field=models.UUIDField(default='<function uuid4 at 0x7fcc9e23ad30>', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='payer',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('safebox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box', to='financialmanager.safebox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
