# Generated by Django 3.2.5 on 2021-07-21 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financialmanager', '0003_auto_20210721_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='safebox',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='invite_id',
            field=models.UUIDField(default='<function uuid4 at 0x7fbe2d1d7d30>', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='payer',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to=settings.AUTH_USER_MODEL),
        ),
    ]
