# Generated by Django 3.2.5 on 2021-07-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financialmanager', '0004_auto_20210721_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='invite_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='members',
            field=models.ManyToManyField(related_name='safebox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='payer',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to=settings.AUTH_USER_MODEL),
        ),
    ]
